export const GET_ALL_DATA = "GET_ALL_DATA";
export const GET_SPECIFIC_DATA = "GET_SPECIFIC_DATA";
export const ADD__BOOKMARKS = "ADD__BOOKMARKS";
export const SET__BOOKMARKS = "SET__BOOKMARKS";
export const CLEAR_ALL_BOOKMARKS = "CLEAR_ALL_BOOKMARKS";
export const CLEAR_SINGLE_BOOKMARK = "CLEAR_SINGLE_BOOKMARK";
export const DATA_LOADING = "DATA_LOADING";
export const DATA_ERROR = "DATA_ERROR";
